import pytest
import unittest
from os_hound.scoring import Scoring


class TestScoring(unittest.TestCase):

    def test_scoring(self):
        # Arrange
        # profile_os = {'SEQ': {'SP': 160, 'GCD': 1, 'ISR': 159, 'TI': 'I', 'CI': 'I', 'TS': '1'},
        #                    'OPS': {'O1': 'Mffd7NW8ST11', 'O2': 'Mffd7NW8ST11', 'O3': 'Mffd7NW8NNT11', 'O4': 'Mffd7NW8ST11', 'O5': 'Mffd7NW8ST11',
        #                            'O6': 'Mffd7ST11'},
        #                    'WIN': {'W1': 65535, 'W2': 65535, 'W3': 65535, 'W4': 65535, 'W5': 65535, 'W6': 65500},
        #                    'ECN': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'W': 65535, 'O': "M0xNW8NNSb''", 'CC': 'N', 'Q': ''},
        #                    'T1': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'S': 'O', 'A': 'O', 'F': 'AS', 'RD': 0, 'Q': ''},
        #                    'T2': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'W': 0, 'S': 'Z', 'F': 'AR', 'RD': 0, 'Q': ''},
        #                    'T3': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'W': 0, 'S': 'Z', 'F': 'AR', 'RD': 0, 'Q': ''},
        #                    'T4': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'W': 0, 'S': 'Z', 'F': 'R', 'RD': 0, 'Q': ''},
        #                    'T5': {'R': 'Y', 'DF': 'N', 'T': 192, 'TG': 128, 'W': 65535, 'S': 'Z', 'F': 'AS', 'RD': 0, 'Q': ''},
        #                    'T6': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'W': 0, 'S': 'Z', 'F': 'R', 'RD': 0, 'Q': ''},
        #                    'T7': {'R': 'Y', 'DF': 'Y', 'T': 192, 'TG': 128, 'W': 0, 'S': 'Z', 'F': 'AR', 'RD': 0, 'Q': ''},
        #                    'U1': {'R': 'Y', 'DF': 'N', 'T': 192, 'TG': 128, 'IPL': 56, 'UN': None, 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': '0xa278',
        #                           'RUD': 'G'},
        #                    'IE': {'R': 'Y', 'DFI': 'N', 'T': 192, 'TG': 128, 'CD': 'Z'}}
        # os_dicts = [
        #     {'SEQ': {'SP': '0-5', 'GCD': '51E80C|A3D018|F5B824|147A030|199883C', 'ISR': 'C8-D2', 'TI': 'I|RD', 'CI': 'I', 'II': 'RI', 'SS': 'S', 'TS': 'U'},
        #      'OPS': {'O1': 'M5B4', 'O2': 'M5B4', 'O3': 'M5B4', 'O4': 'M5B4', 'O5': 'M5B4', 'O6': 'M5B4'},
        #      'WIN': {'W1': '8000', 'W2': '8000', 'W3': '8000', 'W4': '8000', 'W5': '8000', 'W6': '8000'},
        #      'ECN': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'O': 'M5B4', 'CC': 'N', 'Q': ''},
        #      'T1': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''}, 'T2': {'R': 'N'},
        #      'T3': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'S': 'O', 'A': 'S+', 'F': 'AS', 'O': 'M5B4', 'RD': '0', 'Q': ''},
        #      'T4': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'S': 'A+', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
        #      'T5': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'S': 'A', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
        #      'T6': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'S': 'A', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
        #      'T7': {'R': 'Y', 'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'S': 'A', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
        #      'U1': {'DF': 'N', 'T': 'FA-104', 'TG': 'FF', 'IPL': '38', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
        #      'IE': {'DFI': 'S', 'T': 'FA-104', 'TG': 'FF', 'CD': 'S'},
        #      'os_title': ' Fingerprint 2N Helios IP VoIP doorbell Class 2N | embedded || specialized CPE cpe:/h:2n:helios'},
        #     {'SEQ': {'SP': '6A-BE', 'GCD': '1-6', 'ISR': '96-A0', 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': 'A'},
        #      'OPS': {'O1': 'M5B4NNSW0NNNT11', 'O2': 'M578NNSW0NNNT11', 'O3': 'M280W0NNNT11', 'O4': 'M218NNSW0NNNT11', 'O5': 'M218NNSW0NNNT11',
        #              'O6': 'M109NNSNNT11'}, 'WIN': {'W1': '8000', 'W2': '8000', 'W3': '8000', 'W4': '8000', 'W5': '8000', 'W6': '8000'},
        #      'ECN': {'R': 'Y', 'DF': 'Y', 'T': 'FA-104', 'TG': 'FF', 'W': '8000', 'O': 'M5B4NNSW0N', 'CC': 'N', 'Q': ''},
        #      'T1': {'R': 'Y', 'DF': 'Y', 'T': 'FA-104', 'TG': 'FF', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''}, 'T2': {'R': 'N'}, 'T3': {'R': 'N'},
        #      'T4': {'R': 'Y', 'DF': 'Y', 'T': 'FA-104', 'TG': 'FF', 'W': '0', 'S': 'A', 'A': 'Z', 'F': 'R', 'O': '', 'RD': 'E44A4E43', 'Q': ''},
        #      'T5': {'R': 'Y', 'DF': 'Y', 'T': 'FA-104', 'TG': 'FF', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '1F59B3D4', 'Q': ''},
        #      'T6': {'R': 'Y', 'DF': 'Y', 'T': 'FA-104', 'TG': 'FF', 'W': '0', 'S': 'A', 'A': 'Z', 'F': 'R', 'O': '', 'RD': '1F59B3D4', 'Q': ''},
        #      'T7': {'R': 'N'},
        #      'U1': {'DF': 'Y', 'T': 'FA-104', 'TG': 'FF', 'IPL': '70', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
        #      'IE': {'DFI': 'Y', 'T': 'FA-104', 'TG': 'FF', 'CD': 'S'},
        #      'os_title': ' Fingerprint 2Wire BT2700HG-V ADSL modem Class 2Wire | embedded || broadband router CPE cpe:/h:2wire:bt2700hg-v'}
        # ]
        profile_os = {'SEQ': {'SP': 257, 'GCD': 1, 'ISR': 265, 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': 10},
                      'OPS': {'O1': 'MFFD7NW8ST11', 'O2': 'MFFD7NW8ST11', 'O3': 'MFFD7NW8NNT11', 'O4': 'MFFD7NW8ST11', 'O5': 'MFFD7NW8ST11', 'O6': 'MFFD7ST11'},
                      'WIN': {'W1': 65535, 'W2': 65535, 'W3': 65535, 'W4': 65535, 'W5': 65535, 'W6': 65500},
                      'ECN': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 65535, 'O': 'MFFD7NW8NNS', 'CC': 'N', 'Q': ''},
                      'T1': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': 0, 'Q': ''},
                      'T2': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 0, 'S': 'Z', 'A': 'Z', 'F': 'AR', 'RD': 0, 'Q': ''},
                      'T3': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 0, 'S': 'Z', 'A': 'O', 'F': 'AR', 'RD': 0, 'Q': ''},
                      'T4': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 0, 'S': 'Z', 'A': 'Z', 'F': 'R', 'RD': 0, 'Q': ''},
                      'T5': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 0, 'S': 'Z', 'A': 'S+', 'F': 'AR', 'RD': 0, 'Q': ''},
                      'T6': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 0, 'S': 'Z', 'A': 'Z', 'F': 'R', 'RD': 0, 'Q': ''},
                      'T7': {'R': 'Y', 'DF': 'Y', 'T': 128, 'TG': 128, 'W': 0, 'S': 'Z', 'A': 'S+', 'F': 'AR', 'RD': 0, 'Q': ''},
                      'U1': {'R': 'Y', 'DF': 'N', 'T': 128, 'TG': 128, 'IPL': 356, 'UN': 0, 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
                      'IE': {'R': 'Y', 'DFI': 'N', 'T': 128, 'TG': 128, 'CD': 'Z'}}
        os_dicts = [{'SEQ': {'SP': 'F5-FF', 'GCD': '1-6', 'ISR': '10A-114', 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': '7'},
                     'OPS': {'O1': 'M5ACNW8ST11', 'O2': 'M5ACNW8ST11', 'O3': 'M5ACNW8NNT11', 'O4': 'M5ACNW8ST11', 'O5': 'M5ACNW8ST11', 'O6': 'M5ACST11'},
                     'WIN': {'W1': '2000', 'W2': '2000', 'W3': '2000', 'W4': '2000', 'W5': '2000', 'W6': '2000'},
                     'ECN': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '2000', 'O': 'M5ACNW8NNS', 'CC': 'N', 'Q': ''},
                     'T1': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''},
                     'T2': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T3': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'O', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T4': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T5': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T6': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T7': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'U1': {'DF': 'N', 'T': '7B-85', 'TG': '80', 'IPL': '164', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
                     'IE': {'DFI': 'N', 'T': '7B-85', 'TG': '80', 'CD': 'Z'},
                     'os_title': ' Fingerprint Microsoft Windows 7 Class Microsoft | Windows | 7 | general purpose CPE cpe:/o:microsoft:windows_7 auto'},
                    {'SEQ': {'SP': '104-10E', 'GCD': '1-6', 'ISR': '106-110', 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': 'A'},
                     'OPS': {'O1': 'M5BCNW8ST11', 'O2': 'M5BCNW8ST11', 'O3': 'M5BCNW8NNT11', 'O4': 'M5BCNW8ST11', 'O5': 'M5BCNW8ST11', 'O6': 'M5BCST11'},
                     'WIN': {'W1': '2000', 'W2': '2000', 'W3': '2000', 'W4': '2000', 'W5': '2000', 'W6': '2000'},
                     'ECN': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '2000', 'O': 'M5BCNW8NNS', 'CC': 'N', 'Q': ''},
                     'T1': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''},
                     'T2': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T3': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'O', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T4': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T5': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T6': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T7': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'U1': {'DF': 'N', 'T': '7B-85', 'TG': '80', 'IPL': '164', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
                     'IE': {'DFI': 'N', 'T': '7B-85', 'TG': '80', 'CD': 'Z'},
                     'os_title': ' Fingerprint Microsoft Windows 10 1507 Class Microsoft | Windows | 10 | general purpose CPE cpe:/o:microsoft:windows_10:1507 auto'},
                    {'SEQ': {'SP': 'FE-108', 'GCD': '1-6', 'ISR': '102-10C', 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': 'A'},
                     'OPS': {'O1': 'M5B4ST11', 'O2': 'M5B4ST11', 'O3': 'M5B4NNT11', 'O4': 'M5B4ST11', 'O5': 'M5B4ST11', 'O6': 'M5B4ST11'},
                     'WIN': {'W1': 'FE88', 'W2': 'FED4', 'W3': 'FF20', 'W4': 'FFDC', 'W5': 'FFDC', 'W6': 'FFDC'},
                     'ECN': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': 'FAF0', 'O': 'M5B4NNS', 'CC': 'N', 'Q': ''},
                     'T1': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''},
                     'T2': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T3': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'O', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T4': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T5': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T6': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T7': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'U1': {'DF': 'N', 'T': '7B-85', 'TG': '80', 'IPL': '164', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
                     'IE': {'DFI': 'N', 'T': '7B-85', 'TG': '80', 'CD': ''},
                     'os_title': ' Fingerprint Microsoft Windows 11 21H2 Class Microsoft | Windows | 11 | general purpose'},
                    {'SEQ': {'SP': 'FE-108', 'GCD': '1-6', 'ISR': '107-111', 'TI': 'I', 'II': 'I', 'SS': 'S', 'TS': 'A'},
                     'OPS': {'O1': 'M5B4NW8ST11', 'O2': 'M5B4NW8ST11', 'O3': 'M5B4NW8NNT11', 'O4': 'M5B4NW8ST11', 'O5': 'M5B4NW8ST11', 'O6': 'M5B4ST11'},
                     'WIN': {'W1': 'FFFF', 'W2': 'FFFF', 'W3': 'FFFF', 'W4': 'FFFF', 'W5': 'FFFF', 'W6': 'FFDC'},
                     'ECN': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': 'FFFF', 'O': 'M5B4NW8NNS', 'CC': 'N', 'Q': ''},
                     'T1': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''}, 'T2': {'R': 'N'},
                     'T3': {'R': 'N'}, 'T4': {'R': 'N'},
                     'T5': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T6': {'R': 'N'}, 'T7': {'R': 'N'},
                     'U1': {'DF': 'N', 'T': '7B-85', 'TG': '80', 'IPL': '164', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'G', 'RUCK': 'G', 'RUD': 'G'},
                     'IE': {'DFI': 'N', 'T': '7B-85', 'TG': '80', 'CD': 'Z'},
                     'os_title': ' Fingerprint Microsoft Windows 11 21H2 Class Microsoft | Windows | 11 | general purpose'},
                    {'SEQ': {'SP': '100-10A', 'GCD': '1-6', 'ISR': '101-10B', 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': 'A'},
                     'OPS': {'O1': 'MFFD7ST11', 'O2': 'MFFD7ST11', 'O3': 'MFFD7NNT11', 'O4': 'MFFD7ST11', 'O5': 'MFFD7ST11', 'O6': 'MFFD7ST11'},
                     'WIN': {'W1': 'FE88', 'W2': 'FED4', 'W3': 'FF20', 'W4': 'FFDC', 'W5': 'FFDC', 'W6': 'FFDC'},
                     'ECN': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': 'FAF0', 'O': 'MFFD7NNS', 'CC': 'N', 'Q': ''},
                     'T1': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''},
                     'T2': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T3': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'O', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T4': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T5': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T6': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T7': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'U1': {'DF': 'N', 'T': '7B-85', 'TG': '80', 'IPL': '164', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'Z', 'RUCK': 'G', 'RUD': 'G'},
                     'IE': {'DFI': 'N', 'T': '7B-85', 'TG': '80', 'CD': 'Z'},
                     'os_title': ' Fingerprint Microsoft Windows 11 21H2 Class Microsoft | Windows | 11 | general purpose'},
                    {'SEQ': {'SP': 'E8-F2', 'GCD': '1-6', 'ISR': '105-10F', 'TI': 'I', 'CI': 'I', 'II': 'I', 'SS': 'S', 'TS': 'U'},
                     'OPS': {'O1': 'MFFD7NW8NNS', 'O2': 'MFFD7NW8NNS', 'O3': 'MFFD7NW8', 'O4': 'MFFD7NW8NNS', 'O5': 'MFFD7NW8NNS', 'O6': 'MFFD7NNS'},
                     'WIN': {'W1': 'FFFF', 'W2': 'FFFF', 'W3': 'FFFF', 'W4': 'FFFF', 'W5': 'FFFF', 'W6': 'FF70'},
                     'ECN': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': 'FFFF', 'O': 'MFFD7NW8NNS', 'CC': 'N', 'Q': ''},
                     'T1': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'S': 'O', 'A': 'S+', 'F': 'AS', 'RD': '0', 'Q': ''},
                     'T2': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T3': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'O', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T4': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T5': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'T6': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'A', 'A': 'O', 'F': 'R', 'O': '', 'RD': '0', 'Q': ''},
                     'T7': {'R': 'Y', 'DF': 'Y', 'T': '7B-85', 'TG': '80', 'W': '0', 'S': 'Z', 'A': 'S+', 'F': 'AR', 'O': '', 'RD': '0', 'Q': ''},
                     'U1': {'DF': 'N', 'T': '7B-85', 'TG': '80', 'IPL': '164', 'UN': '0', 'RIPL': 'G', 'RID': 'G', 'RIPCK': 'Z', 'RUCK': 'G', 'RUD': 'G'},
                     'IE': {'DFI': 'N', 'T': '7B-85', 'TG': '80', 'CD': ''},
                     'os_title': ' Fingerprint Microsoft Windows 11 21H2 Class Microsoft | Windows | 11 | general purpose'}
                    ]
        instance = Scoring()

        # Act
        result = instance.score(profile_os, os_dicts)

        # Assert
        assert (result[0][0]['os_title'], ' Fingerprint 2N Helios IP VoIP doorbell Class 2N | embedded || specialized CPE cpe:/h:2n:helios')


if __name__ == "__main__":
    pytest.main()
